# Generated by Django 5.0.7 on 2024-08-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipie_name', models.CharField(max_length=100)),
                ('recipie_description', models.TextField()),
                ('recipie_image', models.ImageField(upload_to='recipie')),
            ],
        ),
    ]
