# Generated by Django 5.0.7 on 2024-08-22 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b44d2ea0-a7b8-4be3-9903-91dd40dfe43b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
