# Generated by Django 5.0.7 on 2024-08-22 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9d90b4cf-6834-4456-af50-86b788b48b9e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
