# Generated by Django 5.0.7 on 2024-08-23 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_alter_todo_created_at_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('35c1cebd-4bc8-409c-8313-c51716711324'), editable=False, primary_key=True, serialize=False),
        ),
    ]
