# Generated by Django 5.0.7 on 2024-08-23 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('307a9ca4-7139-41df-8cf6-55e45b12765a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
