# Generated by Django 5.0.7 on 2024-08-23 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1aba25f5-5b4c-4690-8c2e-d40c1dca621f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
