# Generated by Django 5.0.7 on 2024-08-23 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0013_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5ce25a70-ae7a-406e-8b94-4ac4de88cd10'), editable=False, primary_key=True, serialize=False),
        ),
    ]
