# Generated by Django 5.0.7 on 2024-08-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0017_timingtodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['user']},
        ),
    ]
