# Generated by Django 5.0.7 on 2024-08-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0018_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['user']},
        ),
    ]
